"""Common constants."""
ADMIN_URL = "admin/"
BUTTON_TEXT = "button_text"
INDEX = "index"
LABELS_URL = "labels/"
LOGIN = "login"
LOGIN_URL = "login/"
LOGOUT = "logout"
LOGOUT_URL = "logout/"
STATUSES_URL = "statuses/"
TASKS_URL = "tasks/"
TITLE = "title"
USERS_URL = "users/"
