"""Constants for tasks app."""
TASKS = "tasks"
AUTHOR = "author"
EXECUTOR = "executor"
TASKS_CHANGE = "tasks:change"
TASKS_DELETE = "tasks:delete"
TASKS_CREATE = "tasks:create"
TASKS_LIST = "tasks:list"
TASKS_URL = "tasks/"
