"""Constants for users app."""
PASSWORD2 = "password2"
PASSWORD1 = "password1"
USERNAME = "username"
LAST_NAME = "last_name"
FIRST_NAME = "first_name"
USERS_DELETE = "users:delete"
USERS_CHANGE = "users:change"
USERS_CREATE = "users:create"
USERS = "users"
USERS_LIST = "users:list"
USERS_URL = "users/"
USERS_TEST = "/users/"
