STATUSES_DELETE = "statuses:delete"
STATUSES_CHANGE = "statuses:change"
STATUSES_CREATE = "statuses:create"
STATUSES_LIST = "statuses:list"
STATUSES = "statuses"
STATUS = "status"
STATUSES_URL = "statuses/"
